#!/bin/bash
#
# FlowLogic WMS - One-Click Installer
# Works on Linux, macOS, and Windows (WSL/Git Bash)
#
# Usage: curl -fsSL https://flowlogic.io/install.sh | bash
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# FlowLogic ASCII Art
echo -e "${BLUE}"
cat << "EOF"
  _____ _               _                _
 |  ___| | _____      _| |    ___   __ _(_) ___
 | |_  | |/ _ \ \ /\ / / |   / _ \ / _` | |/ __|
 |  _| | | (_) \ V  V /| |__| (_) | (_| | | (__
 |_|   |_|\___/ \_/\_/ |_____\___/ \__, |_|\___|
                                   |___/
    Warehouse Management System - Installer
EOF
echo -e "${NC}"

echo ""
echo "=============================================="
echo "  FlowLogic WMS Installation"
echo "=============================================="
echo ""

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        OS="linux"
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        OS="macos"
    elif [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
        OS="windows"
    else
        OS="unknown"
    fi
    echo -e "${GREEN}Detected OS: $OS${NC}"
}

# Check prerequisites
check_prerequisites() {
    echo ""
    echo "Checking prerequisites..."

    # Check Node.js
    if command -v node &> /dev/null; then
        NODE_VERSION=$(node -v)
        echo -e "  ${GREEN}✓${NC} Node.js $NODE_VERSION"
    else
        echo -e "  ${RED}✗${NC} Node.js not found"
        echo ""
        echo "Please install Node.js 18+ from https://nodejs.org"
        exit 1
    fi

    # Check npm
    if command -v npm &> /dev/null; then
        NPM_VERSION=$(npm -v)
        echo -e "  ${GREEN}✓${NC} npm $NPM_VERSION"
    else
        echo -e "  ${RED}✗${NC} npm not found"
        exit 1
    fi

    # Check Docker (optional)
    if command -v docker &> /dev/null; then
        DOCKER_VERSION=$(docker --version | cut -d ' ' -f 3 | tr -d ',')
        echo -e "  ${GREEN}✓${NC} Docker $DOCKER_VERSION (optional)"
        DOCKER_AVAILABLE=true
    else
        echo -e "  ${YELLOW}○${NC} Docker not found (optional - for containerized deployment)"
        DOCKER_AVAILABLE=false
    fi

    # Check Git
    if command -v git &> /dev/null; then
        GIT_VERSION=$(git --version | cut -d ' ' -f 3)
        echo -e "  ${GREEN}✓${NC} Git $GIT_VERSION"
    else
        echo -e "  ${RED}✗${NC} Git not found"
        echo ""
        echo "Please install Git from https://git-scm.com"
        exit 1
    fi
}

# Installation directory
INSTALL_DIR="${FLOWLOGIC_DIR:-$HOME/flowlogic-wms}"

# Create installation directory
create_install_dir() {
    echo ""
    echo "Installation directory: $INSTALL_DIR"

    if [ -d "$INSTALL_DIR" ]; then
        echo -e "${YELLOW}Directory exists. Updating...${NC}"
    else
        mkdir -p "$INSTALL_DIR"
        echo -e "${GREEN}Created installation directory${NC}"
    fi
}

# Clone or update repository
install_flowlogic() {
    echo ""
    echo "Downloading FlowLogic WMS..."

    cd "$INSTALL_DIR"

    if [ -d ".git" ]; then
        echo "Updating existing installation..."
        git pull origin main
    else
        echo "Cloning repository..."
        git clone https://github.com/flowlogic-wms/flowlogic-ui.git .
    fi

    echo -e "${GREEN}✓ Download complete${NC}"
}

# Install dependencies
install_dependencies() {
    echo ""
    echo "Installing dependencies..."

    cd "$INSTALL_DIR"
    npm install

    echo -e "${GREEN}✓ Dependencies installed${NC}"
}

# Setup environment
setup_environment() {
    echo ""
    echo "Setting up environment..."

    cd "$INSTALL_DIR"

    if [ ! -f ".env" ]; then
        cat > .env << 'ENVFILE'
# FlowLogic WMS Configuration
# Generated by installer

# Server Configuration
PORT=3001
NODE_ENV=production

# Database Configuration
# Option 1: PostgreSQL (recommended for production)
DATABASE_URL="postgresql://flowlogic:flowlogic@localhost:5432/flowlogic_wms?schema=public"

# Option 2: SQLite (for quick start / demos)
# DATABASE_URL="file:./flowlogic.db"

# AI Assistant (optional - get key from https://console.anthropic.com)
ANTHROPIC_API_KEY=

# JWT Secret (auto-generated)
JWT_SECRET=flowlogic_jwt_secret_change_in_production

# ERP Integration Settings
# Uncomment and configure as needed

# SAP Configuration
# SAP_HOST=
# SAP_CLIENT=
# SAP_USER=
# SAP_PASSWORD=
# SAP_SYSTEM_NUMBER=

# Oracle ERP Configuration
# ORACLE_HOST=
# ORACLE_PORT=
# ORACLE_SERVICE=
# ORACLE_USER=
# ORACLE_PASSWORD=

# NetSuite Configuration
# NETSUITE_ACCOUNT_ID=
# NETSUITE_CONSUMER_KEY=
# NETSUITE_CONSUMER_SECRET=
# NETSUITE_TOKEN_ID=
# NETSUITE_TOKEN_SECRET=

# Microsoft Dynamics Configuration
# DYNAMICS_TENANT_ID=
# DYNAMICS_CLIENT_ID=
# DYNAMICS_CLIENT_SECRET=
# DYNAMICS_ENVIRONMENT=

# EDI/FTP Configuration
# EDI_FTP_HOST=
# EDI_FTP_USER=
# EDI_FTP_PASSWORD=
# EDI_FTP_INBOUND_PATH=/inbound
# EDI_FTP_OUTBOUND_PATH=/outbound
ENVFILE
        echo -e "${GREEN}✓ Environment file created${NC}"
    else
        echo -e "${YELLOW}○ Environment file already exists${NC}"
    fi
}

# Setup database
setup_database() {
    echo ""
    echo "Setting up database..."

    cd "$INSTALL_DIR"

    # Generate Prisma client
    npx prisma generate

    # Push schema to database
    npx prisma db push --accept-data-loss 2>/dev/null || {
        echo -e "${YELLOW}Note: Database connection failed. Using demo mode.${NC}"
        echo "To use a real database, edit .env and run: npx prisma db push"
    }

    echo -e "${GREEN}✓ Database setup complete${NC}"
}

# Build application
build_application() {
    echo ""
    echo "Building application..."

    cd "$INSTALL_DIR"
    npm run build

    echo -e "${GREEN}✓ Build complete${NC}"
}

# Create startup scripts
create_startup_scripts() {
    echo ""
    echo "Creating startup scripts..."

    cd "$INSTALL_DIR"

    # Linux/Mac startup script
    cat > start.sh << 'STARTSH'
#!/bin/bash
cd "$(dirname "$0")"
echo "Starting FlowLogic WMS..."
echo ""
echo "  Web UI:  http://localhost:5173"
echo "  API:     http://localhost:3001"
echo ""
echo "Press Ctrl+C to stop"
echo ""
npm run dev
STARTSH
    chmod +x start.sh

    # Windows startup script
    cat > start.bat << 'STARTBAT'
@echo off
cd /d "%~dp0"
echo Starting FlowLogic WMS...
echo.
echo   Web UI:  http://localhost:5173
echo   API:     http://localhost:3001
echo.
echo Press Ctrl+C to stop
echo.
npm run dev
STARTBAT

    # Production startup
    cat > start-production.sh << 'PRODSH'
#!/bin/bash
cd "$(dirname "$0")"
echo "Starting FlowLogic WMS (Production)..."
node server/index.js &
npx serve -s dist -l 5173 &
echo ""
echo "FlowLogic WMS is running!"
echo "  Web UI:  http://localhost:5173"
echo "  API:     http://localhost:3001"
PRODSH
    chmod +x start-production.sh

    echo -e "${GREEN}✓ Startup scripts created${NC}"
}

# Create systemd service (Linux)
create_systemd_service() {
    if [[ "$OS" == "linux" ]] && command -v systemctl &> /dev/null; then
        echo ""
        echo "Creating systemd service..."

        SERVICE_FILE="/etc/systemd/system/flowlogic.service"

        sudo tee $SERVICE_FILE > /dev/null << SERVICEEOF
[Unit]
Description=FlowLogic WMS
After=network.target postgresql.service

[Service]
Type=simple
User=$USER
WorkingDirectory=$INSTALL_DIR
ExecStart=/usr/bin/node $INSTALL_DIR/server/index.js
Restart=on-failure
RestartSec=10
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
SERVICEEOF

        sudo systemctl daemon-reload
        echo -e "${GREEN}✓ Systemd service created${NC}"
        echo "  To start: sudo systemctl start flowlogic"
        echo "  To enable on boot: sudo systemctl enable flowlogic"
    fi
}

# Docker setup
setup_docker() {
    if [ "$DOCKER_AVAILABLE" = true ]; then
        echo ""
        read -p "Do you want to set up Docker deployment? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            cd "$INSTALL_DIR"

            # Create docker-compose.yml if it doesn't exist
            if [ ! -f "docker-compose.yml" ]; then
                cat > docker-compose.yml << 'DOCKERCOMPOSE'
version: '3.8'

services:
  flowlogic:
    build: .
    ports:
      - "3001:3001"
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://flowlogic:flowlogic@db:5432/flowlogic_wms
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=flowlogic
      - POSTGRES_PASSWORD=flowlogic
      - POSTGRES_DB=flowlogic_wms
    volumes:
      - flowlogic_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  flowlogic_data:
DOCKERCOMPOSE
            fi

            echo -e "${GREEN}✓ Docker setup complete${NC}"
            echo "  To start with Docker: docker-compose up -d"
        fi
    fi
}

# Print completion message
print_completion() {
    echo ""
    echo -e "${GREEN}=============================================="
    echo "  Installation Complete!"
    echo "==============================================${NC}"
    echo ""
    echo "FlowLogic WMS has been installed to: $INSTALL_DIR"
    echo ""
    echo -e "${BLUE}To start FlowLogic WMS:${NC}"
    echo ""
    echo "  cd $INSTALL_DIR"
    echo "  ./start.sh          # Development mode"
    echo "  ./start-production.sh  # Production mode"
    echo ""
    echo -e "${BLUE}Access the application:${NC}"
    echo ""
    echo "  Web UI:  http://localhost:5173"
    echo "  API:     http://localhost:3001/api"
    echo ""
    echo -e "${BLUE}Configure ERP Integration:${NC}"
    echo ""
    echo "  Edit .env file to add your ERP credentials"
    echo "  Supported: SAP, Oracle, NetSuite, Microsoft Dynamics"
    echo ""
    echo -e "${BLUE}Documentation:${NC}"
    echo ""
    echo "  https://docs.flowlogic.io"
    echo ""
    echo -e "${YELLOW}Need help? Contact support@flowlogic.io${NC}"
    echo ""
}

# Main installation flow
main() {
    detect_os
    check_prerequisites
    create_install_dir
    install_flowlogic
    install_dependencies
    setup_environment
    setup_database
    build_application
    create_startup_scripts
    create_systemd_service
    setup_docker
    print_completion
}

# Run installer
main
